name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          poetry run pytest
      - name: Run Pylinter
        run: |
          poetry run pylint **/*.py
### Docker Build and Publish
  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Github ghcr registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_TOKEN }}

    - id: release
      uses: rymndhng/release-on-push-action@v0.28.0
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        bump_version_scheme: major
        tag_prefix: v

    - name: publish container
      uses: docker/build-push-action@v5
      with:
        context: ./CloudFlareUpdateIp
        platforms: linux/amd64,linux/arm64,linux/arm/v8
        push: true
        tags:
          ghcr.io/dfoulkes/personal-blog:${{ steps.release.outputs.version }},ghcr.io/dfoulkes/k3s_cloudflare_dynamic_ip_updater:latest
        username: ${{ github.actor }}
        github-token: ${{ secrets.CI_TOKEN }}