name: Scan Branch Commit

on:
  push:
    branches-ignore:
      - main
permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check Build Quality Control
      uses: ./.github/workflows/reusable-quality-control.yml@main
